// Public domain under CC0 1.0. See LICENSE and PATENTS.md.
// SPDX-FileCopyrightText: NONE
// SPDX-License-Identifier: CC0-1.0

// Regenerates server/gate/gate.generated.js from bend/gate.bend via bend/entry.bend.
// Dev only. Users get the committed generated file. Run with: pnpm bend:build
// CI drift check: pnpm bend:check
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { join, dirname } from "node:path";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const outPath = join(root, "server", "gate", "gate.generated.js");
const gitattributesPath = join(root, ".gitattributes");
const check = process.argv.includes("--check");

const REQUIRED_DEFS = [
  "$gate$Gate$decide$",
  "$gate$Policy$default$",
  "$gate$Judgment$stamp$",
  "$gate$Decision$show$",
  "$gate$Reason$show$",
  "$gate$Verdict$show$",
  "$gate$Verdict$read$",
  "$gate$Bp$show$",
];

const BEND_MISSING_MSG =
  "bend >= 2.0.5 is required to regenerate the gate policy (dev only): curl -fsSL https://bend-lang.com/install.sh | sh";

function runBend(args) {
  return execFileSync("bend", args, { cwd: root, encoding: "utf8", stdio: "pipe" });
}

function stripInstallerNoise(text) {
  return text
    .split("\n")
    .filter((line) => !line.includes("Bend's installer changed"))
    .join("\n");
}

function locateBend() {
  try {
    execFileSync("bend", ["--version"], { encoding: "utf8", stdio: "pipe" });
  } catch {
    console.error(BEND_MISSING_MSG);
    process.exit(1);
  }
}

function bendVersion() {
  const raw = runBend(["--version"]);
  const stripped = stripInstallerNoise(raw);
  const match = stripped.match(/bend\s+(\d+\.\d+\.\d+)/);
  return match ? match[1] : "unknown";
}

function checkLaws() {
  let stdout, stderr;
  try {
    const result = execFileSync("bend", ["bend/PROOF.bend"], {
      cwd: root,
      encoding: "utf8",
      stdio: "pipe",
    });
    stdout = stripInstallerNoise(result);
  } catch (err) {
    stdout = stripInstallerNoise(err.stdout ?? "");
    stderr = stripInstallerNoise(err.stderr ?? "");
    console.log(stdout);
    console.log(stderr);
    console.error("laws do not hold; refusing to regenerate");
    process.exit(1);
  }
  if (!stdout.includes("All terms check.")) {
    console.log(stdout);
    console.error("laws do not hold; refusing to regenerate");
    process.exit(1);
  }
}

function compileEntry() {
  const tmpFile = join(tmpdir(), "paseo-spacedock-gate.js");
  try {
    runBend(["bend/entry.bend", "-o", tmpFile]);
  } catch (err) {
    console.error(stripInstallerNoise(err.stderr ?? ""));
    console.error("bend bend/entry.bend -o failed");
    process.exit(1);
  }
  return readFileSync(tmpFile, "utf8");
}

function extractDefs(source) {
  const cliIndex = source.split("\n").findIndex((line) => line === "// Cli");
  if (cliIndex === -1) {
    console.error("could not find // Cli marker in emitted JS");
    process.exit(1);
  }
  const lines = source.split("\n").slice(0, cliIndex);
  const text = lines.join("\n");
  if (!text.includes("// Program")) {
    console.error("emitted JS missing // Program header");
    process.exit(1);
  }
  if (!text.includes("function run_loop(")) {
    console.error("emitted JS missing run_loop runtime helper");
    process.exit(1);
  }
  const impure = text.match(/^\s*(import |export |const .*require\(|.*process\.)/m);
  if (impure) {
    console.error(`emitted JS is not pure: ${impure[0].trim()}`);
    process.exit(1);
  }
  for (const name of REQUIRED_DEFS) {
    if (!text.includes(`function ${name}(`)) {
      console.error(`def ${name} not emitted — is it reached from bend/entry.bend main?`);
      process.exit(1);
    }
  }
  return text;
}

const EXPORTS = `// Exports (added by scripts/bend-build.mjs)
// ================================================
const call = (f) => (...args) => run_loop(f(...args));
export const Gate = {
  decide: call($gate$Gate$decide$),
  policyDefault: call($gate$Policy$default$),
  stamp: call($gate$Judgment$stamp$),
  showDecision: call($gate$Decision$show$),
  showReason: call($gate$Reason$show$),
  showVerdict: call($gate$Verdict$show$),
  readVerdict: call($gate$Verdict$read$),
  showBp: call($gate$Bp$show$),
};`;

function buildOutput(source) {
  const version = bendVersion();
  // REUSE-IgnoreStart
  const header =
    "// Public domain under CC0 1.0. See LICENSE and PATENTS.md.\n" +
    "// SPDX-FileCopyrightText: NONE\n" +
    "// SPDX-License-Identifier: CC0-1.0\n" +
    `// GENERATED by scripts/bend-build.mjs from bend/gate.bend via bend/entry.bend (bend ${version}).\n` +
    "// Do not edit. Regenerate with `pnpm bend:build`; laws in bend/LAWS.bend are checked first.\n";
  // REUSE-IgnoreEnd
  return `${header}${source}\n${EXPORTS}\n`;
}

function ensureGitattributes() {
  let existing = "";
  if (existsSync(gitattributesPath)) {
    existing = readFileSync(gitattributesPath, "utf8");
  }
  const entry = "server/gate/gate.generated.js linguist-generated=true";
  if (existing.includes(entry)) return;
  const next = existing
    ? existing.endsWith("\n")
      ? existing + entry + "\n"
      : existing + "\n" + entry + "\n"
    : entry + "\n";
  writeFileSync(gitattributesPath, next);
}

locateBend();
checkLaws();
const source = compileEntry();
const defs = extractDefs(source);
const output = buildOutput(defs);

if (check) {
  if (!existsSync(outPath)) {
    console.error("server/gate/gate.generated.js is stale; run pnpm bend:build");
    process.exit(1);
  }
  const existing = readFileSync(outPath, "utf8");
  if (existing !== output) {
    console.error("server/gate/gate.generated.js is stale; run pnpm bend:build");
    process.exit(1);
  }
  process.exit(0);
}

writeFileSync(outPath, output);
ensureGitattributes();
